[project]
name = "iot-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awsiotsdk>=1.28.0",
    "boto3>=1.42.30",
    "paho-mqtt>=2.1.0",
]
